### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jmatsushita** [jeprinz/pantograph#3]
Hi there,

Really interesting work! I just finished the tutorial at https://jeprinz.github.io/pantograph/ and had a couple of fresh thoughts:
- Keyboard navigation, I worked my way to understand how to do dragging with only keyboard based navigation, but I think it would be worth a tutorial step!
- On step 13, I struggled a bit on the last task to reinsert the partial applications, I think the instruction should add a note to indicate that when the function is already partially applied to an argument, then to add a new argument to it, you need to select the function with it's outer parens, i.e. "(average" in order to insert new arguments (in last position). 

<img width="344" alt="image" src="https://github.com/user-attachments/assets/a925d34b-a3c7-4b80-a413-dbf33d58ff86">

Otherwise I got into a state where I selected "average" and added a hole in first position which then displayed a type error which I didn't understand at the time (since the lesson on changing the order of arguments comes later).
<img width="268" alt="image" src="https://github.com/user-attachments/assets/62b09919-6803-424b-b57a-82b1558947cd">

- In general, having a tooltip on hover for all underlined errors (for instance above) would be great.

- Checking your code and the network traffic, I don't think you're collecting data about usage about your tutorial, but I believe that it would be understood by your visitors if you mentioned you collected data for academic purposes, and even if you only had numbers about the time spent on each tutorial steps, and how many users completed the tutorial, I think it would be of great academic value to have even some proxy metric about whether your users manage to acquire some fluency after going through your tutorial. Maybe with [purescript-sentry-raven](https://github.com/adamczykm/purescript-sentry-raven) and `captureMessage` and the free Sentry plan? If you wanted to get even more on the HCI side, probably a very simple questionnaire to ask if your visitors ever used a structured editor before, what editor they use daily, what they thought of the tutorial, if they would see themselves switching to a mature version of a structured editor, and what they think are the biggest obstacles for them to adopt a structured editor.

I found myself gathering ease while progressing through the tutorial, without any real experience using a structured editor before (even if I've been keeping an eye on the field for a bit) and that was satisfying and also felt promising. 

Best of luck with your project,

Jun

**Comment by jmatsushita** [comment]
I've now discovered https://github.com/rybla/pantograph-user-study and I see you've published your results in https://arxiv.org/pdf/2411.16571 and will present at POPL so I guess my comment is fairly moot. Cheers!

**Comment by jeprinz** [comment]
@jmatsushita Thanks for the feedback! It a good suggestion to add explicit instructions on the keyboard interface. When it comes to the problems with partial application and argument reordering, we are still working on ways to improve these in future versions, but we agree that these are shortcomings of our approach. Thanks for the suggestions about tracking statistics, we will look into it.
